### ISSUE TITLE
Remove support for automatic configuration

### ISSUE THREAD

**Issue by wenkokke** [wenkokke/setup-agda#155]
Require that the user manually calls `cabal configure` in the pre-build hook if they want anything other than the default customisation. This removes support for the following inputs:
```yaml
  force-cluster-counting:
    description: |
      If specified, build with cluster counting.
    required: false
  force-no-cluster-counting:
    description: |
      If specified, build without cluster counting.
    required: false
  force-optimise-heavily:
    description: |
      If specified, build with optimise heavily.
    required: false
  force-no-optimise-heavily:
    description: |
      If specified, build without optimise heavily.
    required: false
```
Looking towards agdaup, this should add a new `configure-options` option, since passing the entire `cabal configure` command when calling `agdaup build` is counterintuitive. This should potentially result in deprecating the `pre-build-hook` option, in favour of the new `configure-options` option.
