### ISSUE TITLE
`outputs.agda-version` is empty

### ISSUE THREAD

**Issue by andreasabel** [wenkokke/setup-agda#183]
With workflow steps like this:
```yaml
env:
  AGDA_VERSION: 2.6.3
  STDLIB_VERSION: 1.7.1
...
      - name: Setup Agda
        uses: wenkokke/setup-agda@latest
        id:   setup
        with:
          agda-version: ${{ env.AGDA_VERSION }}
          agda-stdlib-version: ${{ env.STDLIB_VERSION }}

      - name: Cache build
        uses: actions/cache@v3
        id:   cache
        with:
          key: agda-${{ steps.setup.outputs.agda-version }}-stdlib-${{ env.STDLIB_VERSION }}
```
I get an empty `steps.setup.outputs.agda-version`, as witnessed in this workflow run:
https://github.com/graded-type-theory/graded-type-theory/actions/runs/5093788246/jobs/9156820105#step:4:3
```
Run actions/cache@v3
  with:
    key: agda--stdlib-1.7.1
```
I am using `latest` (2023-02-07).
